services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - $CERTS_PATH/private.key:/etc/ssl/private/private.key:ro
      - $CERTS_PATH/public.pem:/etc/ssl/certs/public.pem:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - antoha_store

  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    volumes:
      - ../../redis_data:/data
    networks:
      - antoha_store

  app:
    user: "1000:1000"
    build:
      context: ../../app
    env_file:
      - .env
    volumes:
      - ../../app:/app
      - $DOWNLOAD_FILES:/var/www/course/files
    networks:
      - antoha_store
    command: python3 main.py

  bot:
    user: "1000:1000"
    build:
      context: ../../bot
    env_file:
      - .env
    volumes:
      - ../../bot:/bot
      - $DOWNLOAD_FILES:/var/www/course/files
      - $CERTS_PATH/public.pem:/etc/ssl/certs/public.pem:ro
    expose:
      - "8081"
    networks:
      - antoha_store
    command: python3 main.py --webhook

networks:
  antoha_store:
    name: antoha_store
    external: false