services:
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    volumes:
      - ../../redis_data:/data
    networks:
      - antoha_store

  app:
    user: "1000:1000"
    build:
      context: ../../app
    volumes:
      - ../../app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - antoha_store
    command: python3 main.py

  bot:
    user: "1000:1000"
    build:
      context: ../../bot
    volumes:
      - ../../bot:/bot
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - antoha_store
    command: python3 main.py --no-webhook

networks:
  antoha_store:
    name: antoha_store
    external: false